@echo off
echo Cleaning up existing HRMS processes...

echo Killing processes on port 8000 (Backend)...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :8000 ^| findstr LISTENING') do taskkill /F /PID %%a 2>nul

echo Killing processes on port 3535 (Frontend)...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3535 ^| findstr LISTENING') do taskkill /F /PID %%a 2>nul

echo.
echo Ports cleaned. Starting application...
python app.py
