name: Deploy HRMS

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 31.97.206.171 >> ~/.ssh/known_hosts

      #################################################
      # DEV DEPLOY
      #################################################

      - name: Deploy DEV
        if: github.ref == 'refs/heads/dev'
        run: |
          ssh root@31.97.206.171 << 'EOF'
            cd /root/HRMS/dev

            git fetch origin
            git checkout dev
            git pull origin dev

            cd frontend
            npm install
            npm run build

            pm2 restart HRMS-DEV
          EOF

      #################################################
      # LIVE DEPLOY
      #################################################

      - name: Deploy LIVE
        if: github.ref == 'refs/heads/main'
        run: |
          ssh root@31.97.206.171 << 'EOF'
            cd /root/HRMS/live

            git fetch origin
            git checkout main
            git pull origin main

            cd frontend
            npm install
            npm run build

            pm2 restart HRMS-LIVE
          EOF